"""
Total Loss Calculation Module.

This module defines the `TotalLoss` class, which combines the classification loss
and the sparsity-inducing mask loss into a single objective function for optimization.
It utilizes a lambda scheduler to dynamically weight the mask loss during training.
"""

import torch
import torch.nn as nn
from LambdaScheduler import *

class TotalLoss(nn.Module):
    """
    Computes the combined loss for training with learnable masks.

    This module calculates the total loss as a weighted sum of the primary model's
    classification loss (e.g., CrossEntropy, NLLLoss) and the mask's sparsity loss
    (e.g., L1 penalty). The weight of the mask loss is determined by the current
    value of lambda from the provided scheduler.

    Attributes:
        model_loss (nn.Module): The loss function for the classification task.
        lambda_scheduler (LambdaScheduler): The scheduler controlling the regularization weight (lambda).
        mask_loss_function (callable): The function to compute the sparsity loss of the mask.
    """
    # We instantiate with the mask_loss_fucntion, that way, if we want to change the mask_loss funciton we can replace
    # more easily
    def __init__(self, model_loss, mask_loss_function, lambda_scheduler : LambdaScheduler):
        """
        Initializes the TotalLoss module.

        Args:
            model_loss (nn.Module): The primary loss function (e.g., nn.NLLLoss).
            mask_loss_function (callable): Function to calculate the mask's loss (sparsity penalty).
            lambda_scheduler (LambdaScheduler): Scheduler object that provides the current lambda value.
        """
        super(TotalLoss, self).__init__()
        self.model_loss = model_loss
        self.lambda_scheduler = lambda_scheduler
        self.mask_loss_function = mask_loss_function

    #Passed the masK_model as well because we need to use the scheduler and the mask_loss
    def forward(self, pred, target, mask_model):
        """
        Calculates the individual and total losses.

        Args:
            pred (torch.Tensor): The predictions generated by the model.
            target (torch.Tensor): The ground truth labels.
            mask_model (nn.Module): The mask model containing the learnable mask parameters.

        Returns:
            tuple: A tuple containing three tensors:
                - model_loss: The calculated classification loss.
                - mask_loss: The calculated sparsity loss.
                - total: The combined loss (model_loss + lambda * mask_loss).
        """
        model_loss = self.model_loss(pred, target)
        mask_loss = self.mask_loss_function(mask_model)
        total = model_loss + self.lambda_scheduler.lbd * mask_loss
        return model_loss, mask_loss, total